services:
  frontend:
    image: ghcr.io/khaelano/threading-fe:main
    ports:
      - 80:80
    environment:
      VITE_API_HOST: backend
    networks:
      - internal-net
    depends_on:
      - back-end

  backend:
    image: ghcr.io/khaelano/threading-be:main
    ports:
      - 80:80
    networks:
      - internal-net
    secrets:
      - db_url
      - jwt_secret
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - internal-net
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  db_url:
    external: true
  jwt_secret:
    external: true

networks:
  internal-net:
    driver: overlay

volumes:
  pgdata:
